### ISSUE TITLE
Phase 1 - Project Plan

### ISSUE THREAD

**Issue by abhume** [deco3500-2017/3-Amigos#6]
Identify the key tasks that need to be completed and when.

- [x] Project phases (research, requirements, design, construction, user testing)

- [x] Key deliverable for each phase

- [x] Resources that might be needed
